// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-lCEsHDycolnKqwn1MRrklgqE9LDG2hU',
    appId: '1:252531861206:web:eabe37769a3e606891cb77',
    messagingSenderId: '252531861206',
    projectId: 'doctor-appointment-booking-26',
    authDomain: 'doctor-appointment-booking-26.firebaseapp.com',
    storageBucket: 'doctor-appointment-booking-26.firebasestorage.app',
    measurementId: 'G-LBRKBDQ9WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbyFXrU-ToTMuNHGAWzYr7uttFQkJLerA',
    appId: '1:252531861206:android:9992950f5974bc4a91cb77',
    messagingSenderId: '252531861206',
    projectId: 'doctor-appointment-booking-26',
    storageBucket: 'doctor-appointment-booking-26.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-lCEsHDycolnKqwn1MRrklgqE9LDG2hU',
    appId: '1:252531861206:web:86cb1ba7d98650b391cb77',
    messagingSenderId: '252531861206',
    projectId: 'doctor-appointment-booking-26',
    authDomain: 'doctor-appointment-booking-26.firebaseapp.com',
    storageBucket: 'doctor-appointment-booking-26.firebasestorage.app',
    measurementId: 'G-DJ50GQS3H6',
  );
}
